on:
  push:
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Set vars for build only if not on main"
        run: |
          echo "PAGES_BRANCH=test-pages" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'
      - name: "Set vars for deploy if on main"
        run: |
          echo "PAGES_BRANCH=gh-pages" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: .
          TOKEN: ${{ secrets.ACTBOT_PAT }}
          PAGES_BRANCH: ${{ env.PAGES_BRANCH }}
